Fix swifttemplate rsync call failing sometimes (#382)
* Fix swifttemplate rsync call failing sometimes

From time to time, I have this kind of error while working with swifttemplates:
```
error: rsync: delete_file: rmdir "/var/folders/pw/_psd2lwx3xs2vq5dsq7s7_t80000gn/T/SourceryRuntime.framework/Headers" failed: Directory not empty (66)
rsync: delete_file: rmdir "/var/folders/pw/_psd2lwx3xs2vq5dsq7s7_t80000gn/T/SourceryRuntime.framework/Modules" failed: Directory not empty (66)
rsync: delete_file: rmdir "/var/folders/pw/_psd2lwx3xs2vq5dsq7s7_t80000gn/T/SourceryRuntime.framework/Resources" failed: Directory not empty (66)
rsync: delete_file: rmdir "/var/folders/pw/_psd2lwx3xs2vq5dsq7s7_t80000gn/T/SourceryRuntime.framework/Versions/Current" failed: Directory not empty (66)
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/main.c(996) [sender=2.6.9]
```

And this cannot be solved until I have deleted the framework in this folder.
To work around this problem, I have added the `--force` option in `rsync` which
seems to fix the issue.

I think this issue happens when the SourceryRuntime framework changes. So it
can happen a lot when you are working on Sourcery but should happen less
frequently in the classic use case where only version updates changes it.

* Add CHANGELOG entry